VinylRecordsApp/Models/AddRecordViewModel.cs
namespace VinylRecordsApp.Models
{
    public class AddRecordViewModel
    {
        public string Name { get; set; }

        public string Label { get; set; }

        public int Price { get; set; }

        public DateTime ReleaseDate { get; set; }

        public string Description { get; set; }
    }
}

VinylRecordsApp/Models/Domain/Vinyl.cs
namespace VinylRecordsApp.Models.Domain
{
    public class Vinyl
    {
        public Guid Id { get; set; }

        public string Name { get; set; }

        public string Label { get; set; }

        public int Price { get; set; }

        public DateTime ReleaseDate { get; set; }

        public string Description { get; set; }
    }
}

VinylRecordsApp/Models/ErrorViewModel.cs
namespace VinylRecordsApp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

VinylRecordsApp/Models/UpdateRecordViewModel.cs
namespace VinylRecordsApp.Models
{
    public class UpdateRecordViewModel
    {
        public Guid Id { get; set; }

        public string Name { get; set; }

        public string Label { get; set; }

        public int Price { get; set; }

        public DateTime ReleaseDate { get; set; }

        public string Description { get; set; }
    }
}

VinylRecordsApp/Controllers/VinylController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using VinylRecordsApp.Data;
using VinylRecordsApp.Models;
using VinylRecordsApp.Models.Domain;

namespace VinylRecordsApp.Controllers
{
    public class VinylController : Controller
    {
        private readonly VinylContext vinylContext;
        public VinylController(VinylContext vinylContext)
        {
            this.vinylContext = vinylContext;
        }

        [HttpGet]
        public async Task<IActionResult> Index(string SearchString,string sortOrder)
        {
            ViewData["CurrentFilter"] = SearchString;
            ViewData["DateSort"] = sortOrder == "Date" ? "date_desc" : "Date";
            var records = from b in vinylContext.VinylRecords select b;

            switch (sortOrder)
            {
                case "Date":
                    records = records.OrderBy(b => b.ReleaseDate);
                    break;
                case "date_desc":
                    records = records.OrderByDescending(b => b.ReleaseDate);
                    break;

            }
            if (!String.IsNullOrEmpty(SearchString))
            {
               records =  records.Where(b => b.Description.Contains(SearchString));
            }
            return View(await records.ToListAsync()); 
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Add(AddRecordViewModel addRecordView)
        {
            var vinylRecord = new Vinyl()
            {
                Id = Guid.NewGuid(),
                Name = addRecordView.Name,
                Label = addRecordView.Label,
                Price = addRecordView.Price,
                ReleaseDate = addRecordView.ReleaseDate,
                Description = addRecordView.Description
            };

            await vinylContext.VinylRecords.AddAsync(vinylRecord);
            await vinylContext.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> View(Guid id)
        {
            var record = await vinylContext.VinylRecords.FirstOrDefaultAsync(x => x.Id == id);

            if (record != null)
            {
                var viewModel = new UpdateRecordViewModel()
                {
                    Id = record.Id,
                    Name = record.Name,
                    Label = record.Label,
                    Price = record.Price,
                    ReleaseDate = record.ReleaseDate,
                    Description = record.Description
                };
                return await Task.Run(() => View("View",viewModel));
            }

           

            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> View(UpdateRecordViewModel model)
        {
            var record = await vinylContext.VinylRecords.FindAsync(model.Id);

            if(record != null)
            {
                record.Name = model.Name;
                record.Label = model.Label;
                record.Price =  model.Price;
                record.ReleaseDate = model.ReleaseDate;
                record.Description = model.Description;

                await vinylContext.SaveChangesAsync();

                return RedirectToAction("Index");
              
            }
            return RedirectToAction("Index"); 
        }

        [HttpPost]
        public async Task<IActionResult> Delete(UpdateRecordViewModel model)
        {
            var record = await vinylContext.VinylRecords.FindAsync(model.Id);
            if(record != null)
            {
                vinylContext.VinylRecords.Remove(record);
                await vinylContext.SaveChangesAsync();

                return RedirectToAction("Index");
            }

            return RedirectToAction("Index");
        }

    }
}

VinylRecordsApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

VinylRecordsApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - VinylRecordsApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/VinylRecordsApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Vinyl" asp-action="Index">VinylRecordsApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Vinyl" asp-action="Add">Add Record</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - VinylRecordsApp 
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

VinylRecordsApp/Views/Vinyl/Add.cshtml
@model VinylRecordsApp.Models.AddRecordViewModel

@{
}
<h1>Add Vinyl Record</h1>
<form method="post" action="Add" class="mt-5">
    <div class="mb-3">
        <label for="" class="form-label">Name</label>
        <input type="text" class="form-control" asp-for="Name">
    </div>
    <div class="mb-3">
        <label for="" class="form-label">Label</label>
        <input type="text" class="form-control" asp-for="Label">
    </div>
    <div class="mb-3">
        <label for="" class="form-label">Price</label>
        <input type="number" class="form-control" asp-for="Price">
    </div>
    <div class="mb-3">
        <label for="" class="form-label">Release Date</label>
        <input type="date" class="form-control" asp-for="ReleaseDate">
    </div>
    <div class="mb-3">
        <label for="" class="form-label">Description</label>
        <input type="text" class="form-control" asp-for="Description">
    </div>

    <button type="submit" class="btn btn-primary">Submit</button>
</form>

VinylRecordsApp/Views/Vinyl/Index.cshtml
@model List<VinylRecordsApp.Models.Domain.Vinyl>
  

<h1>Vinyl Records</h1>

<form asp-action="Index" method="get" class="mt-5">
    <label>Search by Description</label>
    <div class="input-group mt-3">
        <input type="text" name="SearchString" class="form-control rounded" placeholder="Search" aria-label="Search"
               value="@ViewData["CurrentFilter"]" />
         <input type="submit" value="Search" class="btn btn-dark" />
    </div>
</form>
<a asp-action="Index">Back to full List</a>

<table class="table mt-5">
    <thead class="table-dark">
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Label</th>
            <th>Price</th>
            <th> <a asp-action="Index" asp-route-sortOrder="@ViewData["DateSort"]">Release Date</a></th>
            <th>Description</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Id</td>
                <td>@item.Name</td>
                <td>@item.Label</td>
                <td>@item.Price</td>
                <td>@item.ReleaseDate.ToString("dd-MM-yyyy")</td>
                <td>@item.Description</td>
                <td><a href="Vinyl/View/@item.Id" class="btn btn-info">View</a></td>
            </tr>
        }
    </tbody>
</table>

VinylRecordsApp/Views/Vinyl/View.cshtml
@model VinylRecordsApp.Models.UpdateRecordViewModel;

<h1>Edit Vinyl Record</h1>
<form method="post" action="View" class="mt-5">
    <div class="mb-3">
        <label for="" class="form-label">Id</label>
        <input type="text" class="form-control" asp-for="Id" readonly>
    </div>
    <div class="mb-3">
        <label for="" class="form-label">Name</label>
        <input type="text" class="form-control" asp-for="Name">
    </div>
    <div class="mb-3">
        <label for="" class="form-label">Label</label>
        <input type="text" class="form-control" asp-for="Label">
    </div>
    <div class="mb-3">
        <label for="" class="form-label">Price</label>
        <input type="number" class="form-control" asp-for="Price">
    </div>
    <div class="mb-3">
        <label for="" class="form-label">Release Date</label>
        <input type="date" class="form-control" asp-for="ReleaseDate">
    </div>
    <div class="mb-3">
        <label for="" class="form-label">Description</label>
        <input type="text" class="form-control" asp-for="Description">
    </div>

    <button type="submit" class="btn btn-success">Submit</button>
    <button type="submit" asp-controller="Vinyl" asp-action="Delete" class="btn btn-danger">Delete</button>


</form>